[supervisord]
nodaemon = true
logfile = /tmp/supervisord.log

[program:openvscode-server]
user = XXX
directory = /home/XXX/ygm-tutorial
environment=HOME="/home/XXX",USER="XXX"
redirect_stderr = true
stdout_logfile = /var/log/openvscode-server.log
command = /opt/openvscode-server/bin/openvscode-server --without-connection-token --host 0.0.0.0 --port 3000
